### ISSUE TITLE
Create FASTJavaComment to hold comments

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/FAST-JAVA#31]
presumably:
- block comments (`/* ... */`) would be attached to the node just **after** their position in the AST
- line comments (`// ...`) would be attached to the node just **before** their position in the AST

**Comment by Gabriel-Darbord** [comment]
I agree with the capacity to attach block comments to the following nodes, however all comments should also be able to stand by themselves:
```java
void toBeImplemented() {
  // TODO
}
```
How about when the line comment comes first in a method?
I usually put/see line comments before some statements, rather than at the end of a line:
```java
void f() {
  // explanations
  doStuff();
  doMoreStuff();

  finalize(); // rarer comment placement
}
```
Also we could have a third comment type for Javadoc (`/** ... */`).

**Comment by NicolasAnquetil** [comment]
I did something:
- `FASTJavaComment` using `FASTTComment`
- all `FASTJavaEntity` use `FASTTWithComments` so that all entities can "contain" a comment
- added `isBlockComment`, `isJavadocComment`, and `isLineComment` methods to `FASTJavacomment`
- added a method `withComments` to `JavaSmaCCProgramNodeImporterVisitor`
- with this importer will link `FASTJavacomment` nodes to nearby `FASTJavaEntity`
